In [1]:
import numpy as np

### Add two list

In [8]:
list_two = list(range(1,4))
list_three = list(range(1,4))
#print(list_three)
list_sum = []

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])
print(list_sum)

[2, 12, 36]


### Adding two array

In [24]:
array_two = np.arange(1,4) ** 2
array_three = np.arange(1,4) ** 3
print(array_three + array_two)

## Conventional Method
print('power of 4 array', np.power(np.array([1,2,3]),4))
print('Negative array', np.negative(np.array([1,2,3])))

[ 2 12 36]
power of 4 array [ 1 16 81]
Negative array [-1 -2 -3]


# Multidimentional Array

In [36]:
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)

multi_array = np.array([x, y, z])

print(multi_array)
print(multi_array.shape)

# This data type object (dtype) informs us about the layout of the array


[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


#### linespace

In [46]:
w = np.linspace(1, 10, 11)
print(w)

## Does not want to include the base value ie 10
wb = np.linspace(1, 10, 11, False)
print(wb)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
[1.         1.81818182 2.63636364 3.45454545 4.27272727 5.09090909
 5.90909091 6.72727273 7.54545455 8.36363636 9.18181818]


##### step

In [42]:
b = np.arange(1, 10, 1)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(6,9)

multi_array = np.array([x, y, z])
print(multi_array[1,2]) ## cordinate (x,y) --> (1,2)
print(multi_array.dtype)

5
int64


In [55]:
multi_array = np.array([x, y, z], dtype= np.int16)
multi_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int16)

## Slicing in numpy array

In [58]:
import numpy as np

x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [67]:
# convert np to list
y = x.tolist()
print(y[2:7])

[3, 4, 5, 6, 7]
