In [1]:
import numpy as np

### Add two list

In [8]:
list_two = list(range(1,4))
list_three = list(range(1,4))
#print(list_three)
list_sum = []

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])
print(list_sum)

[2, 12, 36]


### Adding two array

In [24]:
array_two = np.arange(1,4) ** 2
array_three = np.arange(1,4) ** 3
print(array_three + array_two)

## Conventional Method
print('power of 4 array', np.power(np.array([1,2,3]),4))
print('Negative array', np.negative(np.array([1,2,3])))

[ 2 12 36]
power of 4 array [ 1 16 81]
Negative array [-1 -2 -3]


# Multidimentional Array

In [36]:
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)

multi_array = np.array([x, y, z])

print(multi_array)
print(multi_array.shape)

# This data type object (dtype) informs us about the layout of the array


[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


#### linespace

In [46]:
w = np.linspace(1, 10, 11)
print(w)

## Does not want to include the base value ie 10
wb = np.linspace(1, 10, 11, False)
print(wb)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
[1.         1.81818182 2.63636364 3.45454545 4.27272727 5.09090909
 5.90909091 6.72727273 7.54545455 8.36363636 9.18181818]


##### step

In [42]:
b = np.arange(1, 10, 1)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(6,9)

multi_array = np.array([x, y, z])
print(multi_array[1,2]) ## cordinate (x,y) --> (1,2)
print(multi_array.dtype)

5
int64


In [55]:
multi_array = np.array([x, y, z], dtype= np.int16)
multi_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int16)

## Slicing in numpy array

In [58]:
import numpy as np

x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [67]:
# convert np to list
y = x.tolist()
print(y[2:7])

[3, 4, 5, 6, 7]


### Reshaping


In [3]:
import numpy as np
x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
import numpy as np
x = np.arange(9).reshape(3, 5)
print(x)

ValueError: cannot reshape array of size 9 into shape (3,5)

In [5]:
## Now here there are two sets of 3x3 matrix = 18 elements
import numpy as np
x = np.arange(18).reshape(2, 3, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [6]:
## here 3 sets with 3x2 matrix = 18
import numpy as np
x = np.arange(18).reshape(3, 3, 2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


### Slicing of Multidimentional Array

In [10]:
import numpy as np
x = np.arange(18).reshape(3, 2,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [11]:
## slicing
x[1,1]

array([ 9, 10, 11])

In [12]:
x[1,1, 1]

10

In [14]:
x[1, :2]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
x[1, :2, :3]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
## comparison with slicing
comparison_operation = x > 5
print(comparison_operation) ## boolean answer

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]


In [27]:
x[comparison_operation]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [28]:
x[x>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [29]:
x.max()

17

In [30]:
x.min()

0

### Array Shapes

In [31]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
ravelled_array = x.ravel()
print(ravelled_array)

[0 1 2 3 4 5 6 7 8]


In [33]:
flatten_array = x.flatten()
print(flatten_array)

[0 1 2 3 4 5 6 7 8]


In [35]:
ravelled_array[2] = 10000
print(ravelled_array)
print(x)

[    0     1 10000     3     4     5     6     7     8]
[[    0     1 10000]
 [    3     4     5]
 [    6     7     8]]


In [36]:
## No change in flatten Array because it is a copy of original
print(flatten_array)

[0 1 2 3 4 5 6 7 8]


#### Transpose

In [42]:
y = np.arange(9)
y.shape = [3,3]
print("Original Matrix")
print(y)
print("Tranpose Matrix")
print(y.transpose())

Original Matrix
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Tranpose Matrix
[[0 3 6]
 [1 4 7]
 [2 5 8]]


### Resize

In [45]:
print(np.resize(y, (6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


#### Zeros

In [50]:
d = np.zeros(6,)
print(d)
print(d.dtype) ## default dtype for np is FLOAT64

[0. 0. 0. 0. 0. 0.]
float64


In [54]:
print(np.zeros((6), dtype=int))

[0 0 0 0 0 0]


In [55]:
print(np.zeros((2,3), dtype=int))

[[0 0 0]
 [0 0 0]]


In [56]:
print(np.zeros((3,3), dtype=int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


##### Ones

In [58]:
print(np.ones((2,3), dtype=int))

[[1 1 1]
 [1 1 1]]


##### Eye

In [59]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [61]:
np.random.rand(4,4)
## This will generate shape of the array bw 0 & 1

array([[0.57240096, 0.26633254, 0.65228541, 0.1583558 ],
       [0.89321229, 0.90745467, 0.39596861, 0.6198112 ],
       [0.1430213 , 0.8380773 , 0.05524807, 0.77798521],
       [0.19107813, 0.50183115, 0.79121273, 0.8734201 ]])

### Matrix Multiplication

In [62]:
mat_a = np.matrix([0, 3, 5, 5, 3, 2]).reshape(2,3)
print(mat_a)

[[0 3 5]
 [5 3 2]]


In [63]:
mat_b = np.matrix([3, 4, 3, -2, 4, -2]).reshape(3,2)
print(mat_b)

[[ 3  4]
 [ 3 -2]
 [ 4 -2]]


In [64]:
## method 1
mat_a * mat_b

matrix([[ 29, -16],
        [ 32,  10]])

In [68]:
# method 2
product = np.matmul(mat_a, mat_b)
product

matrix([[ 29, -16],
        [ 32,  10]])

In [69]:
# method 3
mat_a @ mat_b

matrix([[ 29, -16],
        [ 32,  10]])

### Stacking

In [82]:
x = np.arange(4).reshape(2, 2)
print(x)
print(x.shape)

[[0 1]
 [2 3]]
(2, 2)


In [86]:
y = np.arange(4, 8).reshape(2, 2)
print(y)
print(y.shape)

[[4 5]
 [6 7]]
(2, 2)


In [84]:
z = np.hstack((x,y))
print(z)
print(z.shape) 

[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [87]:
 z = np.vstack((x,y))
print(z)
print(z.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [88]:
print(z == w)

NameError: name 'w' is not defined